type: environment.insomnia.rest/5.0
schema_version: "5.1"
name: environment-insomnia
meta:
  id: wrk_793c27f4e039452d8daa392c8d14a444
  created: 1764651095465
  modified: 1764651095465
  description: ""
environments:
  name: Base Environment
  meta:
    id: env_d145355f935d429184e69a8d53d9100d
    created: 1764650082306
    modified: 1764735864464
    isPrivate: false
  data:
    url: localhost:8080
    uniqueUrl: 96d739c8
